#!/bin/bash
####### Setting Savers #######
##############################
alias sudo="sudo "
alias ls="ls --color=always -h"
alias lsblk="lsblk --output=label,name,maj:min,ro,size,type,fstype,mountpoint,uuid"
alias steam="HOME=/home/chaos/.steamhome STEAM_FRAME_FORCE_CLOSE=1 steam"
alias axel="axel -an 3"
alias ytdl="youtube-dl --audio-quality=0"


########## Shortcuts ##########
###############################
# Directory Listing (ls)
alias ll="ls -l"
alias la="ll -a"
alias l="la"


# Output Piping (grep)
alias igrep="grep -i"
alias vgrep="grep -v"
alias ivgrep="grep -iv"


# Git
alias g="git"


# Misc
alias sym="ln -s"
alias pamac="yaourt"
alias print="echo -ne"
alias ddstatus='sudo pkill -x dd --signal USR1; sleep 1'

########## Fun Ones ##########
##############################
alias fucking="sudo"
alias elevate="sudo"
