#!/bin/bash
######################
#	Initial Config
######################
export PATH="${HOME}/bin:${PATH}"
bspc config border_width	   		3		#2	3
bspc config window_gap		 		16		#12	16

bspc config split_ratio				0.50	#0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_by_distance		true
bspc config auto_cancel				true
bspc config bottom_padding			-1
bspc config top_padding	-m DVI-D-0	34		#20
bspc config top_padding -m HDMI-0	0
bspc config left_padding			0
bspc config right_padding			0

bspc config normal_border_color		purple
bspc config focused_border_color	green
bspc config presel_border_color		red

bspc monitor DVI-D-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc rule -a steam desktop=^10



################
#	Autostart
################
sxhkd &
nm-applet &
pamac-tray &
xrdb ~/.Xresources &
~/.dotfiles/lemonbar/rubarb &
xsetroot -cursor_name left_ptr
stalonetray -bg \#000000 -d none \
	--grow-gravity=E --icon-gravity=E \
	--geometry=1x1+3820+1060 --max-geometry=0x1 \
	--sticky --icon-size=20 &
# feh --bg-tile --no-fehbg ~/Pictures/wallpapers/pattern_154.gif &
(sleep 2 && feh --bg-tile ~/Pictures/wallpapers/arch-1.jpg) &
