# vim: set ts=4 sts=2 sw=2 et ai:
---
- name: Symlink configuration files to XDG_CONFIG_HOME
  file: src=~/dotfiles/config/{{ item }}
        dest=~/.config/{{ item }}
        state=link
        force=yes
  with_items:
    - bspwm
    - sxhkd
    - lemonbar
