#!/bin/bash
# Package management/updating
pamac-tray &


# Pulseaudio
# pa-applet &


# NetworkManager
pkill nm-applet && nm-applet &


# Bluetooth Management
# blueman-applet &
blueberry-applet &


# Nvidia Settings
nvdock &


echo 08-applets
