# vim: set ts=4 sts=2 sw=2 et ai:
---
- name: Create any missing directories needed for deployment
  file: path=~/{{ item }}
        state=directory
  with_items:
    - .config
    - bin

- name: Symlink configuration files to XDG_CONFIG_HOME
  file: src=~/dotfiles/config/{{ item }}
        dest=~/.config/{{ item }}
        state=link
        force=yes
  with_items:
    - conky
    - bspwm
    - sxhkd
    - openbox
    - lemonbar
    - yaourt
    - pacman
    - awesome

- name: Symlink dotfiles to $HOME
  file: src=~/dotfiles/home/{{ item }}
        dest=~/.{{ item }}
        state=link
        force=yes
  with_items:
    - bashrc
    - bash_colors
    - bash_profile
    - bash_aliases
    - Xresources

- name: Symlink scripts/binaries to HOME/bin
  file: src=~/dotfiles/bin/{{ item }}
        dest=~/bin/{{ item }}
        state=link
        force=yes
  with_items:
    - conserv
    - mousefix
    - xlocker
